#!/usr/bin/env python
"""Build the Karpathy-style `llm-wiki/` from the knowledge database.

Reads items + predictions + market views + channels + sources + per-item
speaker lists from Postgres and renders a human-readable, densely
cross-linked Markdown wiki under `llm-wiki/`. READ-ONLY against the DB;
writes only to `llm-wiki/` (plus the optional bio cache, see below).

Incremental: re-running updates every generated page **in place** — the
tree is never wiped, files are only rewritten when their content changes,
and any other files you keep in ``llm-wiki/`` are left untouched. Pages a
previous run generated that no longer exist in the DB are garbage-collected
via a manifest at ``scripts/.llm_wiki_manifest.json``.

    uv run python scripts/build_llm_wiki.py [--no-bios]

Sections:

- ``Tickers/``   one page per asset with enough mentions, plus a
                 rates / bond-yield backdrop section for context.
- ``Analysts/``  one page per channel with extracted content.
- ``People/``    one page per *person* — interview guests, show hosts and
                 solo authors alike — with their opinions per topic and
                 how those opinions changed over time (stance flips are
                 detected and flagged). People appearing on several shows
                 get a single merged page.
- ``Themes/``    cross-cutting theses inferred from the predictions.
- ``Syntheses/`` multi-dimensional cut-views: opinion shifts (same person
                 changing stance), disagreements (different people on
                 opposite sides of the same topic), and a global timeline
                 of every extracted call.

People bios: for people who look like finance-industry professionals
(interviewees, researchers, ...), a short bio is generated with the
configured default LLM provider (``zai`` / GLM, model ``glm-5.3`` unless
overridden via ``--model``) and cached in ``scripts/llm_wiki_bios.json``
so re-runs don't re-call the API. Use ``--no-bios`` to skip bio generation
entirely. If the LLM is unavailable, the page renders a DB-derived stub
instead.

The wiki reflects DB state at generation time. Re-run after new scrapes /
extraction batches to refresh.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import text

# Make `kb` importable when run as a script from the repo root.
REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from kb.db import engine  # noqa: E402

WIKI_DIR = REPO / "llm-wiki"
BIO_CACHE = REPO / "scripts" / "llm_wiki_bios.json"
# Bio generation model. Defaults to the provider's configured model except
# on zai, where the wiki pins the newest GLM (5.3) regardless of ZAI_MODEL
# — extraction (kb extract run) keeps using ZAI_MODEL until it is bumped.
WIKI_ZAI_MODEL = "glm-5.3"
# Files generated by the previous run (used to garbage-collect pages that
# no longer exist; kept outside llm-wiki/ so it never shows up in the tree).
MANIFEST = REPO / "scripts" / ".llm_wiki_manifest.json"

# --- thresholds (keep pages meaningful; thin data gets noted, not padded) -----
MIN_TICKER_MENTIONS = 2      # a ticker needs >=2 prediction rows for its own page
MIN_ANALYST_ITEMS = 1        # any channel with an extracted item gets a page
MIN_PERSON_APPEARANCES = 1   # any person seen on an extracted item gets a page
MAX_QUOTE_LEN = 220          # truncate long quotes in summaries

# item.extraction_status literals (kept as named constants so the SQL below
# can bind them as parameters instead of inlining quoted literals)
ST_DONE = "done"
ST_PENDING = "pending"
ST_ERROR = "error"
UNKNOWN_LANG = "(unknown)"


# ---------------------------------------------------------------------------
# Theme taxonomy. A theme groups tickers + market views whose asset name/class
# matches any keyword. This is a hand-curated set derived from the
# asset_class/asset_name spread observed in the DB. Buckets are keyword-based
# so the mapping survives minor LLM wording variance.
# ---------------------------------------------------------------------------
THEMES: list[dict[str, Any]] = [
    {
        "slug": "precious-metals",
        "title": "Precious Metals (Gold, Silver, Platinum, Palladium)",
        "blurb": (
            "Calls on the four precious metals — dominated by gold (GC=F), "
            "with silver (SI=F), platinum (PL=F) and palladium (PA=F). "
            "Gold is the single most-predicted asset in the DB."
        ),
        # "gold" is whole-word matched (so "Goldman Sachs" does not match);
        # see _theme_match.
        "keywords": ["gold", "silver", "platinum", "palladium",
                     "precious metal",
                     "GC=F", "SI=F", "PL=F", "PA=F"],
    },
    {
        "slug": "oil-energy",
        "title": "Oil & Energy",
        "blurb": (
            "Crude oil (CL=F, RB=F), the Strategic Petroleum Reserve, and "
            "broader energy-sector views. Often tied to geopolitics "
            "(Strait of Hormuz, Iran)."
        ),
        "keywords": ["crude oil", "wti", "brent", "oil price", "oil",
                     "CL=F", "RB=F", "strategic petroleum", "energy"],
    },
    {
        "slug": "rates-bonds",
        "title": "Rates, Bonds & the Dollar",
        "blurb": (
            "US Treasury yields (^TNX), the dollar index (DX-Y.NYB), and "
            "broad fixed-income / monetary-policy calls. Rates cuts and "
            "the dollar's reserve status are the recurring threads."
        ),
        "keywords": ["treasury", "10-year", "rates", "bond", "fixed income",
                     "interest rate", "dollar", "dixie", "^TNX", "DX-Y.NYB",
                     "monetary policy", "yen", "JPY=X", "USDJPY"],
    },
    {
        "slug": "ai-semiconductors",
        "title": "AI & Semiconductors",
        "blurb": (
            "The AI / chip-stack trade: Nvidia (NVDA), Micron (MU), the "
            "semiconductor ETF (SMH), and adjacent AI-infrastructure names. "
            "Views split between AI-bubble skeptics and compute bulls."
        ),
        "keywords": ["nvidia", "semiconductor", "ai ", "a.i.", "chip", "micron",
                     "compute", "NVDA", "MU", "MRVL", "SMH", "TER",
                     "openai", "microsoft", "hyperscaler", "anthropic"],
    },
    {
        "slug": "macro-indices",
        "title": "Broad Market & Macro Indices",
        "blurb": (
            "Top-down calls on the S&P 500 (^GSPC, SPY), Nasdaq (^IXIC), "
            "Kospi (^KS11) and macro / economy direction. The "
            "recession-vs-soft-landing debate lives here."
        ),
        "keywords": ["s&p", "sp500", "s&p500", "nasdaq", "^GSPC", "SPY",
                     "^IXIC", "^KS11", "macro", "economy", "gdp",
                     "recession", "depression", "index"],
    },
    {
        "slug": "crypto",
        "title": "Crypto & Stablecoins",
        "blurb": (
            "Bitcoin (BTC-USD) and stablecoin / dollar-peg views. "
            "Crosses into the dedollarization and dollar-theme threads."
        ),
        "keywords": ["bitcoin", "crypto", "stablecoin", "btc", "BTC-USD",
                     "ethereum"],
    },
    {
        "slug": "electrification-industrials",
        "title": "Electrification, Power & Industrials",
        "blurb": (
            "The AI-driven power and electrification build-out: utilities "
            "(NEE, VST, GEV), grid / transformer names (PH, ETN, TKR, POWL, "
            "PWR, PRIM), and the data-center power trade."
        ),
        "keywords": ["utility", "utilities", "power", "electrif",
                     "transformer", "grid", "industrial", "data center",
                     "NEE", "VST", "GEV", "PH", "ETN", "TKR", "POWL", "PWR",
                     "PRIM", "Eaton", "Constellation"],
    },
    {
        "slug": "china-hk-equities",
        "title": "China & Hong Kong Equities",
        "blurb": (
            "Hong Kong / China names and the local macro backdrop — "
            "primarily surfaced from the Chinese-language HKEJ / Master "
            "Insight / Yahoo HK columnists."
        ),
        "keywords": ["hk", "hong kong", "china", "tencent", "alibaba",
                     "jd.com", "京東", "騰訊", "阿里", "港股", "a股",
                     "0700", "海力士"],
    },
    {
        "slug": "uranium-nuclear",
        "title": "Uranium & Nuclear",
        "blurb": (
            "The nuclear renaissance: uranium equities, SMR / OKLO and "
            "data-center baseload power."
        ),
        "keywords": ["uranium", "nuclear", "smr", "oklo", "ccj"],
    },
    {
        "slug": "china-property",
        "title": "China Property & Real Estate",
        "blurb": (
            "Chinese property developers, the mainland real-estate bust and "
            "HK property / land-supply views — mostly from the "
            "Chinese-language columnists."
        ),
        "keywords": ["real estate", "property", "房地產", "地產", "樓市",
                     "楼市", "房價", "房价", "發展商", "开发商", "housing"],
    },
    {
        "slug": "credit-private-credit",
        "title": "Credit, Private Credit & BDCs",
        "blurb": (
            "Credit-cycle views: spreads, private credit / direct lending, "
            "BDCs, structured credit and default risk."
        ),
        "keywords": ["credit", "bdc", "private debt", "private credit",
                     "structured", "default", "high yield", "junk"],
    },
    {
        "slug": "agriculture-food",
        "title": "Agriculture & Softs",
        "blurb": (
            "Grains, softs and food inflation — agriculture calls, often "
            "weather-driven, from the commodities guests."
        ),
        "keywords": ["agriculture", "agricultural", "food", "softs", "wheat",
                     "corn", "soybean", "coffee", "sugar", "cocoa", "DBA",
                     "grain"],
    },
    {
        "slug": "robotics-autonomy",
        "title": "Robotics, Automation & Autonomy",
        "blurb": (
            "Humanoid robotics, factory automation and autonomous driving — "
            "the next-wave productivity bets after the AI build-out."
        ),
        "keywords": ["robotics", "robot", "humanoid", "automation",
                     "autonomous", "self-driving", "robotaxi"],
    },
    {
        "slug": "geopolitics-defense",
        "title": "Geopolitics & Defense",
        "blurb": (
            "War-risk premia, sanctions, tariffs and defense spending — the "
            "geopolitical overlay guests apply to commodities and equities."
        ),
        "keywords": ["geopolit", "defense", "defence", "war ", "tariff",
                     "sanction", "hormuz", "taiwan", "election"],
    },
]

# Rates/bond-yield tickers (Yahoo style) used for the ticker-page backdrop.
RATES_TICKERS = {"^TNX", "^FVX", "^TYX", "^IRX", "ZN=F", "ZF=F", "ZB=F", "ZT=F"}
# Keywords for finding rates/bond-yield *market views* to use as backdrop.
RATES_CONTEXT_KEYWORDS = ["treasury", "rates", "interest rate", "bond",
                          "yield", "monetary policy", "fed", "fomc",
                          "rate cut", "rate hike"]


# ---------------------------------------------------------------------------
# People identity resolution
#
# Speaker names come from LLM extraction and are noisy: "Erik Townsend" vs
# "Eric Townsend", "George" vs "George Noble", generic labels like
# "Host 1" / "作者" / "Eurodollar University host". We resolve every raw
# speaker string to a canonical person (or None for generic labels) via a
# small alias map + generic-pattern filter, then merge that person's
# appearances across ALL shows — so a solo columnist who also guests on
# other podcasts gets one merged page.
# ---------------------------------------------------------------------------

# Raw speaker strings that are NOT a person name.
GENERIC_SPEAKER_PATTERNS = [
    re.compile(r"^\s*(host|speaker|guest|narrator|interviewer|analyst|author"
               r"|co-?host|presenter|moderator|unnamed|unknown)\b", re.I),
    re.compile(r"\bhost\b", re.I),            # "Host 1", "Host (Monetary Matters)"
    re.compile(r"^\s*(speaker|voice)\s*\d*\s*$", re.I),
    re.compile(r"^作者"),                     # "作者", "作者 (Author, …)", "作者（未具名）"
]
GENERIC_SPEAKERS = {"作者", "host", "guest", "guests", "various", "multiple",
                    "unknown", "n/a"}

# Raw -> canonical display name (keys compared lowercased, whitespace-collapsed).
PERSON_ALIASES = {
    "erik townsend": "Erik Townsend",
    "eric townsend": "Erik Townsend",           # common LLM misspelling
    "george": "George Noble",
    "george noble": "George Noble",
    "jeff snider": "Jeff Snider",
    "jeffrey snider": "Jeff Snider",
    "jeffrey christian": "Jeffrey Christian",
    "eurodollar university host": "Jeff Snider",
    "lyn alden": "Lyn Alden",
    "lyn alden roth": "Lyn Alden",
    "jim chanos": "Jim Chanos",
    "james chanos": "Jim Chanos",
    "erik voorhees": "Erik Voorhees",
    "jeff snyder": "Jeff Snider",
    "eurodollar university": "Jeff Snider",
}

# Canonical person -> fragments of channel names they host (lowercase,
# matched by substring). Everyone else on a multi-speaker item is a guest;
# the sole speaker of a single-speaker item is a solo author.
KNOWN_HOSTS: dict[str, list[str]] = {
    "Erik Townsend": ["macro voices"],
    "Patrick Ceresna": ["macro voices"],
    "Jeff Snider": ["eurodollar university"],
    "Raoul Pal": ["raoul pal", "journey man"],
}


def _norm_name(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip()).lower()


def is_generic_speaker(raw: str) -> bool:
    s = (raw or "").strip()
    if not s:
        return True
    if s in GENERIC_SPEAKERS:
        return True
    return any(p.search(s) for p in GENERIC_SPEAKER_PATTERNS)


def resolve_person(raw: str) -> str | None:
    """Canonical display name for a raw speaker string, or None if generic."""
    s = (raw or "").strip()
    if not s or is_generic_speaker(s):
        return None
    key = _norm_name(s)
    if key in PERSON_ALIASES:
        return PERSON_ALIASES[key]
    return re.sub(r"\s+", " ", s)


def host_channels_for(person: str, channel_name: str | None) -> bool:
    """Is `person` a host of the channel called `channel_name`?"""
    frags = KNOWN_HOSTS.get(person, [])
    cn = (channel_name or "").lower()
    return any(f in cn for f in frags)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(s: str) -> str:
    """Filesystem + URL-safe slug. Keeps CJK characters (removed by some
    slugifiers) by falling back to pinyin-free transliteration: CJK runs are
    dropped, and the remaining ascii is cleaned. For pure-CJK strings the
    caller should pass an explicit latin slug instead."""
    s = (s or "").strip().lower()
    s = re.sub(r"[\s/\\?%*:|\"<>]+", "-", s)
    s = re.sub(r"[^a-z0-9._-]", "", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "untitled"


def stance(action: str | None, direction: str | None) -> str:
    """Classify a quote's stance, mirroring api/main.py `_stance`."""
    a = (action or "").strip().lower()
    d = (direction or "").strip().lower()
    bullish_actions = {"buy", "long", "cover"}
    bearish_actions = {"sell", "short", "avoid"}
    if a in bullish_actions or d == "up":
        return "bullish"
    if a in bearish_actions or d == "down":
        return "bearish"
    return "neutral"


def view_stance(direction: str | None) -> str:
    d = (direction or "").strip().lower()
    if d == "bullish":
        return "bullish"
    if d == "bearish":
        return "bearish"
    return "neutral"


STANCE_ARROW = {"bullish": "↑ bullish", "bearish": "↓ bearish",
                "neutral": "→ neutral"}


def truncate(s: str | None, n: int = MAX_QUOTE_LEN) -> str:
    if not s:
        return ""
    s = s.strip().replace("\n", " ")
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def fmt_date(dt: Any) -> str:
    if not dt:
        return "n/d"
    if isinstance(dt, str):
        try:
            dt = datetime.fromisoformat(dt.replace("Z", "+00:00"))
        except ValueError:
            return dt[:10]
    return dt.strftime("%Y-%m-%d")


def md_escape(s: str | None) -> str:
    """Escape pipe chars so text is safe inside markdown tables."""
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def rel_link(path: Path, target_page: str, label: str) -> str:
    """Relative markdown link from `path` (a file) to `target_page` (a wiki
    page name relative to llm-wiki root, without .md)."""
    # number of ../ needed = depth of the file's directory under llm-wiki/
    depth = len(path.parent.relative_to(WIKI_DIR).parts)
    prefix = "../" * depth if depth else ""
    return f"[{label}]({prefix}{target_page}.md)"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def fetch_all() -> dict[str, Any]:
    """Pull everything the wiki needs in one connection."""
    with engine().connect() as c:
        # --- sources + counts ------------------------------------------------
        sources = [dict(r) for r in c.execute(text("""
            SELECT s.code, s.name, s.kind,
                   COUNT(i.id) AS n_items,
                   COUNT(i.id) FILTER (WHERE i.extraction_status = :st_done) AS n_extracted,
                   COUNT(i.id) FILTER (WHERE i.extraction_status = :st_pending) AS n_pending
            FROM source s LEFT JOIN item i ON i.source_id=s.id
            GROUP BY s.id ORDER BY n_items DESC
        """), {"st_done": ST_DONE, "st_pending": ST_PENDING}).mappings()]

        # --- global totals ---------------------------------------------------
        totals = dict(c.execute(text("""
            SELECT COUNT(*) AS n_items,
                   COUNT(*) FILTER (WHERE extraction_status = :st_done) AS n_extracted,
                   COUNT(*) FILTER (WHERE extraction_status = :st_pending) AS n_pending,
                   COUNT(*) FILTER (WHERE extraction_status = :st_error) AS n_error,
                   MIN(published_at) AS first_date,
                   MAX(published_at) AS last_date
            FROM item
        """), {"st_done": ST_DONE, "st_pending": ST_PENDING,
               "st_error": ST_ERROR}).mappings().first())
        n_preds = c.execute(text(
            "SELECT COUNT(*) FROM prediction"
        )).scalar()
        n_views = c.execute(text(
            "SELECT COUNT(*) FROM view_market"
        )).scalar()
        n_channels = c.execute(text(
            "SELECT COUNT(*) FROM channel"
        )).scalar()
        n_tickers = c.execute(text(
            "SELECT COUNT(DISTINCT ticker) FROM prediction WHERE ticker IS NOT NULL"
        )).scalar()
        n_speakers = c.execute(text(
            "SELECT COUNT(DISTINCT speaker) FROM prediction WHERE speaker IS NOT NULL"
        )).scalar()
        # language distribution (top 8)
        langs = [dict(r) for r in c.execute(text("""
            SELECT COALESCE(language, :unknown_lang) AS lang, COUNT(*) AS n
            FROM item GROUP BY language ORDER BY n DESC LIMIT 8
        """), {"unknown_lang": UNKNOWN_LANG}).mappings()]

        # --- predictions (flat, joined to item + channel) --------------------
        preds = [dict(r) for r in c.execute(text("""
            SELECT p.id, p.ticker, p.asset_name, p.speaker, p.action,
                   p.direction, p.target_price, p.stop_price, p.timeframe,
                   p.made_at, p.quote,
                   i.id AS item_id, i.title AS item_title, i.url AS item_url,
                   i.external_id, i.published_at, i.language,
                   c.handle AS channel_handle, c.name AS channel_name,
                   c.id AS channel_id, s.code AS source
            FROM prediction p
            JOIN item i ON i.id=p.item_id
            LEFT JOIN channel c ON c.id=i.channel_id
            LEFT JOIN source s ON s.id=c.source_id
            ORDER BY p.made_at DESC NULLS LAST, p.id DESC
        """)).mappings()]

        # --- market views ----------------------------------------------------
        views = [dict(r) for r in c.execute(text("""
            SELECT v.id, v.speaker, v.asset_class, v.region, v.direction,
                   v.horizon, v.confidence, v.rationale, v.quote,
                   i.id AS item_id, i.title AS item_title, i.url AS item_url,
                   i.published_at,
                   c.handle AS channel_handle, c.name AS channel_name,
                   c.id AS channel_id
            FROM view_market v
            JOIN item i ON i.id=v.item_id
            LEFT JOIN channel c ON c.id=i.channel_id
            ORDER BY i.published_at DESC NULLS LAST
        """)).mappings()]

        # --- per-item speaker lists (from the primary extraction run) --------
        # The whole raw_response jsonb is fetched and the speakers array is
        # read in Python (the driver decodes jsonb to dict). `speakers` is
        # the LLM-extracted list of voices on the item: more than one entry
        # means an interview or panel; a single entry means a solo author
        # or host.
        item_speakers: dict[int, dict] = {}
        for r in c.execute(text("""
            SELECT i.id AS item_id, i.title, i.url, i.published_at,
                   i.channel_id, ch.name AS channel_name,
                   ch.handle AS channel_handle, er.raw_response
            FROM extraction_run er
            JOIN item i ON i.id = er.item_id
            LEFT JOIN channel ch ON ch.id = i.channel_id
            WHERE er.id = i.primary_extraction_run_id
              AND er.raw_response IS NOT NULL
        """)).mappings():
            raw = r["raw_response"]
            if isinstance(raw, dict) and raw.get("speakers") is not None:
                item_speakers[r["item_id"]] = {**dict(r),
                                               "speakers": raw["speakers"]}

        # --- channels with at least one extracted item (analyst pages) -------
        analysts = [dict(r) for r in c.execute(text("""
            SELECT c.id AS channel_id, c.handle AS channel_handle, c.name AS channel_name,
                   c.url, c.metadata, s.code AS source,
                   COUNT(i.id) AS n_extracted,
                   COUNT(DISTINCT i.id) FILTER (
                       WHERE EXISTS (SELECT 1 FROM prediction p
                                     WHERE p.item_id=i.id)) AS n_with_preds
            FROM channel c JOIN source s ON s.id=c.source_id
            JOIN item i ON i.channel_id=c.id
            WHERE i.extraction_status = :st_done
            GROUP BY c.id, c.handle, c.name, c.url, c.metadata, s.code
            ORDER BY n_extracted DESC, c.name
        """), {"st_done": ST_DONE}).mappings()]

        # --- recent extracted items (for Home + analyst "recent calls") ------
        recent_items = [dict(r) for r in c.execute(text("""
            SELECT i.id, i.title, i.url, i.published_at, i.summary, i.language,
                   s.code AS source, c.handle AS channel_handle, c.name AS channel_name
            FROM item i JOIN source s ON s.id=i.source_id
            LEFT JOIN channel c ON c.id=i.channel_id
            WHERE i.extraction_status = :st_done
            ORDER BY i.published_at DESC NULLS LAST LIMIT 40
        """), {"st_done": ST_DONE}).mappings()]

        # --- per-channel extracted item list (analyst link roll) -------------
        channel_items = defaultdict(list)
        for r in c.execute(text("""
            SELECT i.id, i.title, i.url, i.published_at, i.summary,
                   c.id AS channel_id
            FROM item i LEFT JOIN channel c ON c.id=i.channel_id
            WHERE i.extraction_status = :st_done
            ORDER BY i.published_at DESC NULLS LAST
        """), {"st_done": ST_DONE}).mappings():
            channel_items[r["channel_id"]].append(dict(r))

    return {
        "sources": sources,
        "totals": totals,
        "n_preds": n_preds,
        "n_views": n_views,
        "n_channels": n_channels,
        "n_tickers": n_tickers,
        "n_speakers": n_speakers,
        "langs": langs,
        "preds": preds,
        "views": views,
        "item_speakers": item_speakers,
        "analysts": analysts,
        "recent_items": recent_items,
        "channel_items": channel_items,
    }


# ---------------------------------------------------------------------------
# Derived groupings
# ---------------------------------------------------------------------------

# A valid Yahoo-style symbol (used to decide whether a prediction's topic
# page is keyed by ticker or by asset/company name).
SYMBOL_RE = re.compile(r"^[A-Z0-9^.=:\-]{1,12}(\.[A-Z]{1,4})?$")


def _topic_key(p: dict) -> str | None:
    """Page key for a prediction row: the Yahoo symbol when the ticker is
    symbol-like, otherwise the asset/company name (LLMs sometimes emit
    asset-name fragments like 'PAN MINE' into the ticker field; the extract
    pipeline nulls those tickers, so name-keyed grouping picks them up)."""
    tk = (p.get("ticker") or "").strip().upper()
    if tk and SYMBOL_RE.match(tk):
        return tk
    name = (p.get("asset_name") or tk or "").strip()
    return name or None


def topic_page_file(key: str) -> str:
    """Filename (without .md) for a topic page: symbols are used as-is
    (keeps existing pages like ^TNX.md stable), names are slugified."""
    return key if SYMBOL_RE.match(key) else slugify(key)


def group_predictions_by_ticker(preds: list[dict]) -> dict[str, list[dict]]:
    g: dict[str, list[dict]] = defaultdict(list)
    for p in preds:
        k = _topic_key(p)
        if k:
            g[k].append(p)
    return g


def _theme_match(hay: str, keywords: list[str]) -> bool:
    """True if any keyword matches the haystack. Keywords ending in a
    non-word char (e.g. 'gold ') are treated as substring matches; bare
    alphabetic keywords are matched as whole-word tokens (so 'gold' does
    not catch 'Goldman'). Tickers / codes and non-ASCII (CJK) keywords are
    matched as substrings."""
    h = hay.lower()
    for kw in keywords:
        k = kw.lower()
        if not k.isascii():
            # CJK: \b word boundaries don't fire between CJK chars
            if k in h:
                return True
        elif k[-1:] in " =-." or not k.isalpha():
            # codes/tickers contain non-alphanumerics or trailing space → substring
            if k in h:
                return True
        else:
            # whole-word match for plain words
            if re.search(rf"\b{re.escape(k)}\b", h):
                return True
    return False


def ticker_themes(ticker: str, asset_name: str) -> list[str]:
    """Return theme slugs a ticker belongs to."""
    hay = f"{ticker} {asset_name or ''}"
    return [t["slug"] for t in THEMES if _theme_match(hay, t["keywords"])]


def view_themes(v: dict) -> list[str]:
    """Theme slugs a market view belongs to (matched on its text)."""
    hay = " ".join(str(v.get(k) or "") for k in
                   ("asset_class", "region", "rationale", "quote"))
    return [t["slug"] for t in THEMES if _theme_match(hay, t["keywords"])]


def views_for_theme(theme_slug: str) -> list[dict]:
    return [v for v in DATA["views"] if theme_slug in view_themes(v)]


def preds_for_theme(theme_slug: str) -> list[dict]:
    out = []
    for p in DATA["preds"]:
        hay = f"{p.get('ticker','')} {p.get('asset_name','')}"
        if _theme_match(hay, next(t["keywords"] for t in THEMES
                                  if t["slug"] == theme_slug)):
            out.append(p)
    return out


# Shared data loaded once (module global so render helpers can reach it).
DATA: dict[str, Any] = {}
# People registry, filled by build_people(): canonical name -> person dict.
PEOPLE: dict[str, dict] = {}
# Global topic x person matrix (built once in main).
TOPICS: dict[str, dict] = {}


# ---------------------------------------------------------------------------
# People pipeline
# ---------------------------------------------------------------------------

def _effective_speakers(item_id: int) -> list[str]:
    """Resolved canonical speakers on an item (deduped, generics dropped)."""
    rec = DATA["item_speakers"].get(item_id)
    if not rec:
        return []
    out: list[str] = []
    for raw in (rec.get("speakers") or []):
        p = resolve_person(raw)
        if p and p not in out:
            out.append(p)
    return out


def _attributed_speaker(raw_speaker: str | None, item_id: int) -> str | None:
    """Resolve a prediction/view row's speaker to a person. If the row's
    speaker is a generic label, fall back to the item's sole speaker (a
    'Host 1' prediction on a solo-author item belongs to that author)."""
    p = resolve_person(raw_speaker or "")
    if p:
        return p
    eff = _effective_speakers(item_id)
    return eff[0] if len(eff) == 1 else None


def _pred_stance(p: dict) -> str:
    return stance(p.get("action"), p.get("direction"))


def _view_event(v: dict) -> dict:
    return {
        "kind": "view",
        "topic_label": (v.get("asset_class") or "macro").strip(),
        "stance": view_stance(v.get("direction")),
        "date": fmt_date(v.get("published_at")),
        "quote": v.get("quote") or v.get("rationale") or "",
        "ref": v,
    }


def _pred_event(p: dict) -> dict:
    return {
        "kind": "pred",
        "topic_label": p.get("ticker") or (p.get("asset_name") or "?").strip(),
        "stance": _pred_stance(p),
        "date": fmt_date(p.get("made_at") or p.get("published_at")),
        "quote": p.get("quote") or "",
        "ref": p,
    }


def build_people() -> dict[str, dict]:
    """Build the PEOPLE registry: canonical name -> person record with
    appearances (merged across shows), attributed predictions and views."""
    people: dict[str, dict] = {}

    def _get(name: str) -> dict:
        return people.setdefault(name, {
            "name": name,
            "appearances": [],       # {item, role, date, channel info}
            "preds": [],             # attributed prediction rows
            "views": [],             # attributed view rows
        })

    # appearances from per-item speaker lists
    for item_id, rec in DATA["item_speakers"].items():
        eff = _effective_speakers(item_id)
        if not eff:
            continue
        multi = len(eff) > 1
        ch_name = rec.get("channel_name")
        for name in eff:
            role = ("host" if host_channels_for(name, ch_name)
                    else "guest" if multi else "solo")
            _get(name)["appearances"].append({
                "item_id": item_id,
                "role": role,
                "title": rec.get("title"),
                "url": rec.get("url"),
                "published_at": rec.get("published_at"),
                "channel_name": ch_name,
                "channel_handle": rec.get("channel_handle"),
            })

    # attributed predictions / views
    for p in DATA["preds"]:
        name = _attributed_speaker(p.get("speaker"), p.get("item_id"))
        if name:
            _get(name)["preds"].append(p)
    for v in DATA["views"]:
        name = _attributed_speaker(v.get("speaker"), v.get("item_id"))
        if name:
            _get(name)["views"].append(v)

    # stable slugs: latin slug from the name when possible, else a
    # deterministic person-NNN fallback (CJK-only names slugify to empty).
    cjk_idx = 0
    for name in sorted(people):
        sl = slugify(name)
        if sl and sl != "untitled":
            people[name]["slug"] = sl
        else:
            cjk_idx += 1
            people[name]["slug"] = f"person-{cjk_idx:03d}"

    # rollups used by renderers
    for p in people.values():
        p["n_events"] = len(p["preds"]) + len(p["views"])
        p["roles"] = Counter(a["role"] for a in p["appearances"])
        p["channels"] = sorted({a["channel_name"] or a["channel_handle"] or "?"
                                for a in p["appearances"]})
    return people


def person_slug(name: str) -> str | None:
    p = PEOPLE.get(name)
    return p["slug"] if p else None


def _person_has_page(name: str) -> bool:
    """A person gets a page if they have at least one appearance (seen in
    an item's speaker list) or at least one attributed extracted call."""
    p = PEOPLE.get(name)
    return bool(p) and bool(p.get("appearances") or p.get("n_events"))


def person_link(path: Path, name: str) -> str:
    """Markdown link to a person's page (or plain text if no page)."""
    if _person_has_page(name):
        return rel_link(path, f"People/{PEOPLE[name]['slug']}", name)
    return md_escape(name)


# ---------------------------------------------------------------------------
# People bios (LLM-generated, cached)
# ---------------------------------------------------------------------------

BIO_SYSTEM = """You are an encyclopedia editor writing brief, factual bios of
finance-industry people (investors, analysts, economists, newsletter and
research authors, podcast hosts and guests). Output strict JSON per the
schema. Write from general knowledge — being brief is fine and minor
imprecision is acceptable; only leave the fields empty if you genuinely do
not recognize the name at all."""

BIO_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "required": ["role", "bio"],
    "properties": {
        "role": {"type": "string"},   # short descriptor, e.g. "Macro strategist, Lyn Alden Investment Strategy"
        "bio": {"type": "string"},    # 2-4 sentences; empty if not identifiable
        "sells_research": {"type": "boolean"},
    },
}


def _bio_context(person: dict) -> str:
    """Compact DB-derived context about the person for the bio prompt."""
    topics = Counter()
    for p in person["preds"]:
        if p.get("ticker"):
            topics[p["ticker"]] += 1
    shows = Counter(a["channel_name"] or "?" for a in person["appearances"])
    sample_quotes = [truncate(p.get("quote"), 140)
                     for p in person["preds"][:3] if p.get("quote")]
    lines = [f"NAME: {person['name']}"]
    if shows:
        lines.append("APPEARED ON: " +
                     ", ".join(f"{s} (x{n})" for s, n in shows.most_common(5)))
    roles = person.get("roles") or {}
    if roles:
        lines.append("ROLES ON SHOWS: " +
                     ", ".join(f"{r} x{n}" for r, n in roles.most_common()))
    if topics:
        lines.append("MOST-DISCUSSED ASSETS: " +
                     ", ".join(f"{t} ({n})" for t, n in topics.most_common(8)))
    if sample_quotes:
        lines.append("SAMPLE QUOTES:")
        lines += [f'  - "{q}"' for q in sample_quotes]
    return "\n".join(lines)


def ensure_bios(no_llm: bool = False,
                provider: str | None = None,
                model: str | None = None) -> dict[str, dict]:
    """Return the bio cache (canonical name -> bio record), generating any
    missing entries with the LLM. Failures are not cached (retried next
    run); if the LLM is rate-limited/unavailable the whole generation pass
    aborts after the first failure."""
    cache: dict[str, dict] = {}
    if BIO_CACHE.exists():
        try:
            cache = json.loads(BIO_CACHE.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001 — corrupt cache is regenerable
            cache = {}
    if no_llm:
        return cache

    from kb import llm
    from kb.llm import chat_json
    from kb.config import settings
    s = settings()
    provider = provider or s.llm_provider
    if provider not in llm.PROVIDERS:
        print(f"  bios: unknown provider '{provider}' — skipped")
        return cache
    if not llm.has_credentials(provider):
        print(f"  bios: no credentials for provider '{provider}' — skipped")
        return cache
    if model is None:
        model = (WIKI_ZAI_MODEL if provider == "zai"
                 else llm.default_model(provider))

    todo = [n for n in sorted(PEOPLE) if n not in cache]
    if not todo:
        return cache
    print(f"  bios: generating {len(todo)} via {provider}/{model} …")
    for i, name in enumerate(todo, 1):
        person = PEOPLE[name]
        try:
            out = chat_json(BIO_SYSTEM, _bio_context(person), BIO_SCHEMA,
                            provider=provider, model=model)
            # Some models answer with a list of bio objects (e.g. for a
            # multi-person name like "X and Y"); take the first object.
            if isinstance(out, list):
                out = next((x for x in out if isinstance(x, dict)), {})
            if not isinstance(out, dict):
                out = {}
            role = (out.get("role") or " — ".join(
                str(x) for x in (out.get("title"), out.get("affiliation"))
                if x) or "").strip()
            cache[name] = {
                "sells_research": bool(out.get("sells_research")),
                "role": role,
                "bio": (out.get("bio") or "").strip(),
                "provider": provider,
                "model": model,
            }
        except Exception as exc:  # noqa: BLE001
            print(f"  bios: LLM unavailable ({type(exc).__name__}) — "
                  f"stopping after {i-1}/{len(todo)}; stubs will be used")
            break
        if i % 10 == 0:
            print(f"    … {i}/{len(todo)}")
            BIO_CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=1),
                                 encoding="utf-8")
        time.sleep(0.3)
    BIO_CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=1),
                         encoding="utf-8")
    return cache


# ---------------------------------------------------------------------------
# Opinion timelines (per person, per topic)
# ---------------------------------------------------------------------------

def person_topics(person: dict) -> list[dict]:
    """Group a person's attributed predictions + views into topics with a
    chronologically ordered event list (oldest first). Prediction topics
    are tickers; view topics are theme slugs (with a display label)."""
    topics: dict[str, dict] = {}

    def _topic(key: str, label: str, is_ticker: bool) -> dict:
        return topics.setdefault(key, {
            "key": key, "label": label, "is_ticker": is_ticker, "events": []})

    for p in person["preds"]:
        tk = _topic_key(p)
        if not tk:
            continue
        ev = _pred_event(p)
        ev["topic_label"] = tk
        _topic(tk, tk, True)["events"].append(ev)
    for v in person["views"]:
        for slug in view_themes(v):
            theme = next(t for t in THEMES if t["slug"] == slug)
            ev = _view_event(v)
            ev["topic_label"] = slug
            _topic(slug, theme["title"], False)["events"].append(ev)

    for t in topics.values():
        t["events"].sort(key=lambda e: (e["date"] or "", e["ref"].get("id") or 0))
        t["flips"] = detect_flips(t["events"])
        # current stance = most recent directional stance, else last event
        dir_events = [e for e in t["events"] if e["stance"] != "neutral"]
        t["current"] = (dir_events or t["events"])[-1]["stance"] if t["events"] else "neutral"
    return sorted(topics.values(),
                  key=lambda t: (-len(t["events"]), t["label"]))


def detect_flips(events: list[dict]) -> list[tuple[dict, dict]]:
    """Consecutive directional events on a topic whose stance flips between
    bullish and bearish. Returns (before, after) pairs. Only flips that
    span *different days* count — several quotes from the same episode can
    legitimately disagree (hedged language, LLM noise) and are not a
    change of mind over time."""
    flips: list[tuple[dict, dict]] = []
    prev: dict | None = None
    for e in events:
        if e["stance"] == "neutral":
            continue
        if (prev
                and {prev["stance"], e["stance"]} == {"bullish", "bearish"}
                and (e["date"] or "") > (prev["date"] or "")):
            flips.append((prev, e))
        prev = e
    return flips


def build_topic_matrix() -> dict[str, dict]:
    """Topic key -> {label, is_ticker, per_person: name -> events}."""
    for name, person in PEOPLE.items():
        for t in person_topics(person):
            rec = TOPICS.setdefault(t["key"], {
                "key": t["key"], "label": t["label"],
                "is_ticker": t["is_ticker"], "per_person": {}})
            rec["per_person"].setdefault(name, []).extend(t["events"])
    for t in TOPICS.values():
        for evs in t["per_person"].values():
            evs.sort(key=lambda e: (e["date"] or "", e["ref"].get("id") or 0))
    return TOPICS


def topic_link(path: Path, topic: dict) -> str:
    if topic["is_ticker"]:
        # only link topics that actually have their own page (>= threshold
        # predictions); otherwise render as inline code
        n = len(group_predictions_by_ticker(DATA["preds"]).get(topic["key"], []))
        if n >= MIN_TICKER_MENTIONS:
            return rel_link(path, f"Tickers/{topic_page_file(topic['key'])}",
                            topic["key"])
        return f"`{topic['key']}`"
    return rel_link(path, f"Themes/{topic['key']}", topic["label"])


# ---------------------------------------------------------------------------
# Citation helpers
# ---------------------------------------------------------------------------

def item_citation(path: Path, p: dict, *, with_quote: bool = True) -> str:
    """One source-item citation line: '— quote' linked, with date + analyst.

    `path` is the file being rendered (for relative-link depth)."""
    title = (p.get("item_title") or p.get("title") or "untitled").strip()
    url = p.get("item_url") or p.get("url")
    date = fmt_date(p.get("published_at") or p.get("made_at"))
    channel = p.get("channel_name") or p.get("channel_handle") or "?"
    speaker = p.get("speaker")
    by = speaker if speaker and speaker != channel else channel
    by_link = person_link(path, by) if by != channel else md_escape(channel)
    label = title if len(title) <= 80 else title[:79] + "…"
    link = f"[{md_escape(label)}]({url})" if url else md_escape(label)
    cite = f"{link} — {date}, {by_link}"
    if with_quote and p.get("quote"):
        cite += f': "{truncate(p["quote"])}"'
    return cite


def channel_slug(a: dict) -> str:
    """Stable slug for an analyst page. Prefer latin handle, then latin name,
    then a channel-id fallback (for CJK-only handles/names that slugify to
    empty). The display name is always the real channel name; only the URL
    slug is latinized."""
    # Inline slug without the "untitled" fallback so we can detect emptiness.
    def _slug(s: str) -> str:
        s = (s or "").strip().lower()
        s = re.sub(r"[\s/\\?%*:|\"<>]+", "-", s)
        s = re.sub(r"[^a-z0-9._-]", "", s)
        return re.sub(r"-+", "-", s).strip("-")
    handle = (a.get("channel_handle") or "").lstrip("@")
    sh = _slug(handle)
    if sh:
        return sh
    sn = _slug(a.get("channel_name") or "")
    if sn:
        return sn
    # CJK-only handle and name — fall back to a stable id-based slug so each
    # such channel still gets its own distinct page.
    return f"ch-{a.get('channel_id')}"


# ---------------------------------------------------------------------------
# Page renderers
# ---------------------------------------------------------------------------

# Rel paths (posix, under llm-wiki/) written by this run — used for the
# incremental garbage collection in main().
WRITTEN: set[str] = set()


def write_page(rel_path: str, body: str) -> Path:
    p = WIKI_DIR / rel_path
    p.parent.mkdir(parents=True, exist_ok=True)
    content = body.strip() + "\n"
    if not p.exists() or p.read_text(encoding="utf-8") != content:
        p.write_text(content, encoding="utf-8")
    WRITTEN.add(rel_path.replace("\\", "/"))
    return p


def render_home(inv: dict, people_counts: dict[str, int]) -> Path:
    t = inv["totals"]
    lines = [
        "# Knowledge Base Wiki",
        "",
        "> A synthesized, human-readable view of the investment-knowledge "
        "database — what analysts and channels are saying, distilled from "
        "extracted predictions and market views. Karpathy-style: dense links, "
        "honest about uncertainty.",
        "",
        "## What this is",
        "",
        "This wiki is generated directly from the `knowledge_base` Postgres "
        "database: every quote, target price, and stance below is pulled from "
        "an LLM extraction of a real scraped item (YouTube transcript, "
        "HKEJ/Master Insight column, Substack/Patreon post, or blog). Each "
        "claim cites its source item by title, date, channel, and external "
        "URL.",
        "",
        "## Database at a glance",
        "",
        "| | |",
        "|---|---|",
        f"| Total items ingested | **{t['n_items']:,}** |",
        f"| Items extracted (LLM) | **{t['n_extracted']:,}** "
        f"(of {t['n_items']:,}; {t['n_pending']:,} pending) |",
        f"| Predictions extracted | **{inv['n_preds']:,}** |",
        f"| Market views extracted | **{inv['n_views']:,}** |",
        f"| Distinct tickers with calls | **{inv['n_tickers']}** |",
        f"| People with pages | **{people_counts.get('People', 0)}** |",
        f"| Channels (analysts) | **{inv['n_channels']}** |",
        f"| Published-date range | **{fmt_date(t['first_date'])} → {fmt_date(t['last_date'])}** |",
        "",
        "### Sources (by item volume)",
        "",
        "| Source | Kind | Items | Extracted |",
        "|---|---|---:|---:|",
    ]
    for s in inv["sources"]:
        lines.append(
            f"| {md_escape(s['name'])} (`{s['code']}`) | {s['kind']} | "
            f"{s['n_items']:,} | {s['n_extracted']:,} |"
        )
    lines += [
        "",
        "### Languages represented",
        ", ".join(f"`{l['lang']}` ({l['n']:,})" for l in inv["langs"]),
        "",
        "## How to read this wiki",
        "",
        "- **[People/](People)** — one page per *person*: interview guests, "
        "show hosts and solo authors, merged across every show they appear "
        "on. Each page tracks their opinions per topic **over time** and "
        "flags where they changed their mind.",
        "- **[Tickers/](Tickers)** — one page per asset with enough mentions. "
        "Consensus direction, conflict flags, the people on each side, a "
        "rates/bond-yield backdrop, and every source item.",
        "- **[Themes/](Themes)** — cross-cutting theses inferred from the "
        "predictions (AI-semis, gold, oil, rates, electrification, …).",
        "- **[Syntheses/](Syntheses)** — the multi-dimensional views: where "
        "the *same person* flipped stance, where *different people* "
        "disagree on the same topic, and a global timeline of calls.",
        "- **[Analysts/](Analysts)** — one page per channel that has "
        "extracted content, with the people who appear on it.",
        "- **[_Index](_Index)** — flat alphabetical index of every page.",
        "",
        "## ⚠️ Important caveats — read before drawing conclusions",
        "",
        f"1. **Extraction coverage is very thin.** Only **{t['n_extracted']:,}** "
        f"of **{t['n_items']:,}** ingested items have been LLM-extracted so far "
        f"({100*t['n_extracted']/max(t['n_items'],1):.2f}%). Everything below "
        "reflects that small slice — it is **not** a representative sample of "
        "the full corpus. Treat consensus counts as directional, not "
        "authoritative.",
        "2. **No scores yet.** Predictions in this DB carry `score` fields, "
        "but none have been evaluated against market prices (`n_scored=0`). "
        "There is no track record / hit-rate data to report — only stated "
        "calls.",
        "3. **People bios are LLM-written** (from public knowledge + this "
        "DB's context) and can be wrong. Stances/timelines, by contrast, are "
        "strictly DB-derived from extracted quotes.",
        "4. **Channel metadata is sparse.** Most channels have no bio/url in "
        "the DB; analyst pages say so rather than invent.",
        "5. **Re-run to refresh.** After new scrapes/extraction, regenerate "
        "with `uv run python scripts/build_llm_wiki.py` (see "
        "[README](README)).",
        "",
        "## Marquee pages",
        "",
    ]
    # marquee: top people by appearances + top tickers
    by_app = sorted(PEOPLE.values(),
                    key=lambda p: (len(p["appearances"]), p["n_events"]),
                    reverse=True)[:5]
    home = WIKI_DIR / "Home.md"
    for p in by_app:
        lines.append(f"- {rel_link(home, 'People/' + p['slug'], p['name'])}"
                     f" — {len(p['appearances'])} appearance(s), "
                     f"{p['n_events']} extracted call(s)")
    by_tk = group_predictions_by_ticker(inv["preds"])
    top_tk = sorted(by_tk.items(), key=lambda kv: len(kv[1]), reverse=True)[:5]
    for tk, plist in top_tk:
        if len(plist) >= MIN_TICKER_MENTIONS:
            lines.append(f"- [Tickers/{topic_page_file(tk)}](Tickers/{topic_page_file(tk)}.md) — "
                         f"{len(plist)} analyst mentions")
    lines += [
        "",
        "## Recently extracted items",
        "",
    ]
    for it in inv["recent_items"][:12]:
        url = it.get("item_url") or ""
        title = (it.get("title") or "untitled").strip()
        label = title if len(title) <= 90 else title[:89] + "…"
        link = f"[{md_escape(label)}]({url})" if url else md_escape(label)
        ch = it.get("channel_name") or it.get("channel_handle") or "?"
        lines.append(f"- {fmt_date(it['published_at'])} — {link} "
                     f"({md_escape(ch)}, `{it.get('source')}`)")
    return write_page("Home.md", "\n".join(lines))


def _rates_backdrop(path: Path, ticker: str, limit: int = 6) -> list[str]:
    """Lines for the 'rates & bond-yield backdrop' section on a ticker page.
    Returns [] (no section) for rates tickers themselves."""
    if ticker in RATES_TICKERS or "rates-bonds" in ticker_themes(ticker, ""):
        return []
    rows: list[dict] = []
    for v in DATA["views"]:
        hay = " ".join(str(v.get(k) or "") for k in
                       ("asset_class", "region", "rationale"))
        if _theme_match(hay, RATES_CONTEXT_KEYWORDS):
            rows.append(v)
    rows.sort(key=lambda v: fmt_date(v.get("published_at"))
              if v.get("published_at") else "0000-00-00", reverse=True)
    if not rows:
        return []
    lines = [
        "## Rates & bond-yield backdrop",
        "",
        "What the same extracted corpus says about rates / yields — context "
        "for the calls above (most recent first):",
        "",
    ]
    for v in rows[:limit]:
        sp = v.get("speaker") or ""
        sp_l = person_link(path, sp) if sp else ""
        who = sp_l or md_escape(v.get("channel_name") or "?")
        d = v.get("direction") or "?"
        lines.append(f"- {fmt_date(v.get('published_at'))} "
                     f"_{md_escape(d)}_ {who}: "
                     f"\"{truncate(v.get('quote') or v.get('rationale'), 180)}\"")
    lines += ["", f"_See also the "
                  f"{rel_link(path, 'Themes/rates-bonds', 'rates-bonds theme')}._"]
    return lines


def render_ticker(ticker: str, plist: list[dict]) -> Path | None:
    if len(plist) < MIN_TICKER_MENTIONS:
        return None
    is_symbol = bool(SYMBOL_RE.match(ticker))
    asset_name = next((p.get("asset_name") for p in plist if p.get("asset_name")), ticker)
    heading = (f"# {ticker} — {md_escape(asset_name)}" if is_symbol
               and asset_name != ticker else f"# {md_escape(asset_name)}")
    stances = [stance(p.get("action"), p.get("direction")) for p in plist]
    n_bull = sum(1 for s in stances if s == "bullish")
    n_bear = sum(1 for s in stances if s == "bearish")
    n_neut = sum(1 for s in stances if s == "neutral")
    conflict = n_bull > 0 and n_bear > 0
    if n_bull > n_bear:
        consensus = "bullish"
    elif n_bear > n_bull:
        consensus = "bearish"
    elif n_bull == n_bear and n_bull > 0:
        consensus = "mixed (conflict)"
    else:
        consensus = "neutral / watch"

    themes = sorted(set(ticker_themes(ticker, asset_name)))
    speakers = sorted({resolve_person(p.get("speaker") or "") or p.get("speaker")
                       for p in plist if p.get("speaker")})
    channels = sorted({(p.get("channel_handle"), p.get("channel_name"))
                       for p in plist if p.get("channel_handle")})

    rel = f"Tickers/{topic_page_file(ticker)}.md"
    path = WIKI_DIR / rel
    lines = [
        heading,
        "",
        f"**{len(plist)} extracted prediction(s)** across "
        f"{len(channels)} channel(s). Consensus: **{consensus}** "
        f"({n_bull} bullish / {n_bear} bearish / {n_neut} neutral)."
        + (" ⚠️ **Conflict flag**: analysts disagree on direction." if conflict else ""),
        "",
        "## Themes",
        "",
    ]
    if themes:
        for slug in themes:
            theme = next(t for t in THEMES if t["slug"] == slug)
            lines.append(f"- {rel_link(path, f'Themes/{slug}', theme['title'])}")
    else:
        lines.append("_Not bucketed into any theme (single-name / idiosyncratic)._")
    lines += [
        "",
        "## Stance breakdown",
        "",
        "| Stance | Count |",
        "|---|---:|",
        f"| Bullish | {n_bull} |",
        f"| Bearish | {n_bear} |",
        f"| Neutral / watch | {n_neut} |",
        "",
        "## Voices on this ticker",
        "",
    ]
    for sp in speakers:
        lines.append(f"- {person_link(path, sp)}" if sp in PEOPLE
                     else f"- {md_escape(sp)}")
    lines += [
        "",
        "## Notable calls",
        "",
    ]
    # sort newest first; plist already sorted desc by made_at from the query
    for p in plist:
        sp = p.get("speaker") or p.get("channel_name") or "?"
        meta_bits = []
        if p.get("action"):
            meta_bits.append(f"action=`{p['action']}`")
        if p.get("direction"):
            meta_bits.append(f"dir=`{p['direction']}`")
        if p.get("target_price"):
            meta_bits.append(f"target=`{p['target_price']}`")
        if p.get("timeframe"):
            meta_bits.append(f"tf=`{p['timeframe']}`")
        meta = (" (" + ", ".join(meta_bits) + ")") if meta_bits else ""
        lines.append(f"- **{md_escape(sp)}**{meta} — {item_citation(path, p)}")
    lines += [
        "",
        "## Analysts covering this ticker",
        "",
    ]
    for handle, name in channels:
        a = next((x for x in DATA["analysts"]
                  if x["channel_handle"] == handle), None)
        if a:
            slug = channel_slug(a)
            lines.append(f"- {rel_link(path, f'Analysts/{slug}', name or handle)} (`{handle}`)")
        else:
            lines.append(f"- {md_escape(name)} (`{handle}`)")
    # rates / bond-yield backdrop (not on rates tickers themselves)
    lines += ["", *_rates_backdrop(path, ticker)]
    lines += [
        "",
        "## Source items",
        "",
    ]
    seen_items = set()
    for p in plist:
        iid = p.get("item_id")
        if iid in seen_items:
            continue
        seen_items.add(iid)
        title = (p.get("item_title") or "untitled").strip()
        url = p.get("item_url")
        label = title if len(title) <= 90 else title[:89] + "…"
        link = f"[{md_escape(label)}]({url})" if url else md_escape(label)
        lines.append(f"- {fmt_date(p.get('published_at'))} — {link} "
                     f"({md_escape(p.get('channel_name') or p.get('channel_handle') or '?')})")
    lines += [
        "",
        "---",
        f"_Page reflects DB state at generation time. Regenerate via "
        "`uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page(rel, "\n".join(lines))


def render_analyst(a: dict) -> Path:
    cid = a["channel_id"]
    handle = a.get("channel_handle") or "?"
    name = a.get("channel_name") or handle
    slug = channel_slug(a)
    rel = f"Analysts/{slug}.md"
    path = WIKI_DIR / rel

    preds = [p for p in DATA["preds"] if p.get("channel_handle") == handle]
    views = [v for v in DATA["views"] if v.get("channel_handle") == handle]
    items = DATA["channel_items"].get(cid, [])

    # coverage: tickers they call most
    tk_counter = Counter((k for k in (_topic_key(p) for p in preds) if k))
    top_tickers = tk_counter.most_common(10)
    stances = [stance(p.get("action"), p.get("direction")) for p in preds]
    n_bull = sum(1 for s in stances if s == "bullish")
    n_bear = sum(1 for s in stances if s == "bearish")
    n_neut = sum(1 for s in stances if s == "neutral")

    # people who appear on this channel (hosts + guests + solo authors)
    channel_people: list[tuple[str, int, str]] = []
    for pname, p in PEOPLE.items():
        apps = [x for x in p["appearances"]
                if x.get("channel_name") == name or x.get("channel_handle") == handle]
        if apps:
            roles = "/".join(sorted({x["role"] for x in apps}))
            channel_people.append((pname, len(apps), roles))
    channel_people.sort(key=lambda x: (-x[1], x[0]))

    # market-view stance (asset_class level)
    mv_dirs = Counter((v.get("direction") for v in views if v.get("direction")))

    lines = [
        f"# {md_escape(name)}",
        "",
        f"`{handle}` — source: `{a.get('source')}`  ·  "
        f"channel id: `{cid}`",
        "",
    ]
    url = a.get("url")
    if url:
        lines.append(f"**URL**: {url}")
    else:
        lines.append("_No URL / bio in DB channel metadata._")
    lines += [
        "",
        "## Coverage profile",
        "",
        f"- **Extracted items**: {a['n_extracted']}",
        f"- **Items with predictions**: {a.get('n_with_preds', 0)}",
        f"- **Predictions**: {len(preds)}",
        f"- **Market views**: {len(views)}",
        "",
    ]
    if channel_people:
        lines += [
            "## People on this channel",
            "",
            "(hosts, guests and solo authors — each person's appearances "
            "across all shows are merged on their own People page)",
            "",
        ]
        for pname, n, roles in channel_people[:20]:
            lines.append(f"- {person_link(path, pname)} — {n} appearance(s) "
                         f"as {roles}")
        lines.append("")
    if top_tickers:
        lines += ["**Most-called tickers:**", ""]
        for tk, n in top_tickers:
            ticker_link = (rel_link(path, f"Tickers/{topic_page_file(tk)}", tk)
                           if tk in group_predictions_by_ticker(DATA["preds"])
                           and len(group_predictions_by_ticker(DATA["preds"])[tk]) >= MIN_TICKER_MENTIONS
                           else f"`{tk}`")
            lines.append(f"- {ticker_link} ({n})")
        lines.append("")
    if preds:
        lines += [
            "## Stance distribution (predictions)",
            "",
            "| Stance | Count |",
            "|---|---:|",
            f"| Bullish | {n_bull} |",
            f"| Bearish | {n_bear} |",
            f"| Neutral / watch | {n_neut} |",
            "",
        ]
    if views and sum(mv_dirs.values()):
        lines += [
            "## Market-view direction",
            "",
            "| Direction | Count |",
            "|---|---:|",
        ]
        for d, n in mv_dirs.most_common():
            lines.append(f"| {md_escape(d)} | {n} |")
        lines.append("")
    if preds:
        lines += ["## Recent notable calls", ""]
        for p in preds[:8]:
            tk = _topic_key(p) or "(no ticker)"
            tk_link = (rel_link(path, f"Tickers/{topic_page_file(tk)}", tk)
                       if tk in group_predictions_by_ticker(DATA["preds"])
                       and len(group_predictions_by_ticker(DATA["preds"])[tk]) >= MIN_TICKER_MENTIONS
                       else f"`{tk}`")
            lines.append(f"- {tk_link}: {item_citation(path, p)}")
        lines.append("")
    if views:
        lines += ["## Recent market views", ""]
        for v in views[:6]:
            ac = v.get("asset_class") or "?"
            d = v.get("direction") or "?"
            lines.append(f"- _{md_escape(ac)} — {md_escape(d)}_: "
                         f"{item_citation(path, v)}")
        lines.append("")
    if items:
        lines += [
            "## Source items (extracted)",
            "",
        ]
        for it in items[:25]:
            url = it.get("url")
            title = (it.get("title") or "untitled").strip()
            label = title if len(title) <= 90 else title[:89] + "…"
            link = f"[{md_escape(label)}]({url})" if url else md_escape(label)
            lines.append(f"- {fmt_date(it.get('published_at'))} — {link}")
        if len(items) > 25:
            lines.append(f"_…and {len(items)-25} more._")
        lines.append("")
    if not preds and not views:
        lines += [
            "_This channel has extracted items but no predictions or market "
            "views surfaced yet (the extraction may have found none, or the "
            "content is non-marketable commentary)._",
            "",
        ]
    lines += [
        "---",
        f"_Page reflects DB state at generation time._",
    ]
    return write_page(rel, "\n".join(lines))


def render_person(person: dict, bios: dict[str, dict]) -> Path:
    name = person["name"]
    slug = person["slug"]
    rel = f"People/{slug}.md"
    path = WIKI_DIR / rel
    apps = sorted(person["appearances"],
                  key=lambda a: fmt_date(a.get("published_at")), reverse=True)
    topics = person_topics(person)
    all_flips = [(t, f) for t in topics for f in t["flips"]]
    n_stances = Counter(e["stance"] for t in topics for e in t["events"])

    lines = [
        f"# {md_escape(name)}",
        "",
    ]

    # --- bio ---------------------------------------------------------------
    bio = bios.get(name) or {}
    hosted = [ch for ch in person["channels"]
              if host_channels_for(name, ch)]
    role_bits = []
    if hosted:
        role_bits.append(f"host of {', '.join(md_escape(h) for h in hosted)}")
    r = person["roles"]
    if r.get("guest"):
        role_bits.append(f"interview guest ({r['guest']}x)")
    if r.get("solo"):
        role_bits.append(f"solo author/host ({r['solo']}x)")
    if role_bits:
        lines.append("**" + " · ".join(role_bits) + "**")
        lines.append("")
    if bio.get("bio") or bio.get("role"):
        if bio.get("role"):
            role_line = f"**Role:** {md_escape(bio['role'])}"
            if bio.get("sells_research"):
                role_line += " — *publishes/sells research*"
            lines += [role_line, ""]
        if bio.get("bio"):
            lines += [f"> {md_escape(bio['bio'])}", "",
                      "_Bio LLM-generated from public knowledge + this DB's "
                      "context — verify before relying on it. Everything "
                      "below the bio is strictly DB-derived._", ""]
    else:
        lines += ["_No finance-industry bio established (LLM bio unavailable "
                  "or not a finance professional); the page below is "
                  "DB-derived only._", ""]

    # --- at a glance -------------------------------------------------------
    dates = [fmt_date(a.get("published_at")) for a in apps if a.get("published_at")]
    lines += [
        "## At a glance",
        "",
        f"- **Appearances**: {len(apps)}"
        + (f" ({dates[-1]} → {dates[0]})" if dates else ""),
        f"- **Shows**: {', '.join(md_escape(c) for c in person['channels'])}",
        f"- **Extracted calls**: {len(person['preds'])} predictions, "
        f"{len(person['views'])} market views",
    ]
    if topics:
        lines.append(f"- **Topics with opinions**: {len(topics)}"
                     + (f", **{len(all_flips)} stance flip(s)** ⚠️"
                        if all_flips else ""))
        lines.append(f"- **Stance split**: "
                     f"{n_stances.get('bullish',0)} bullish / "
                     f"{n_stances.get('bearish',0)} bearish / "
                     f"{n_stances.get('neutral',0)} neutral")
    lines.append("")

    # --- appearances -------------------------------------------------------
    if apps:
        lines += ["## Appearances", "",
                  "| Date | Show | Role | Item |", "|---|---|---|---|"]
        for a in apps:
            title = (a.get("title") or "untitled").strip()
            label = title if len(title) <= 60 else title[:59] + "…"
            link = f"[{md_escape(label)}]({a['url']})" if a.get("url") \
                else md_escape(label)
            lines.append(f"| {fmt_date(a.get('published_at'))} | "
                         f"{md_escape(a.get('channel_name') or '?')} | "
                         f"{a['role']} | {link} |")
        lines.append("")

    # --- opinions by topic, over time ---------------------------------------
    if topics:
        lines += [
            "## Opinions by topic, over time",
            "",
            "_Oldest → newest within each topic. Arrows show each call's "
            "stance; ⚠️ marks a detected change of mind._",
            "",
        ]
        for t in topics:
            flip_dates = {f[1]["date"] for f in t["flips"]}
            head = (f"### {topic_link(path, t)}"
                    + f" — now **{t['current']}** ({len(t['events'])} call(s))"
                    + (" ⚠️ stance flipped" if t["flips"] else ""))
            lines += [head, ""]
            for e in t["events"]:
                mark = " ⚠️ **flip**" if e["date"] in flip_dates else ""
                lines.append(f"- `{e['date']}` {STANCE_ARROW[e['stance']]}"
                             f"{mark} — {truncate(e['quote'], 180) or '_(no quote)'}")
            lines.append("")

    # --- opinion shifts -----------------------------------------------------
    if all_flips:
        lines += [
            "## Opinion shifts",
            "",
            "Where this person changed their stance on the same topic:",
            "",
        ]
        for t, (before, after) in all_flips:
            lines.append(f"- **{topic_link(path, t)}**: "
                         f"`{before['date']}` {STANCE_ARROW[before['stance']]} "
                         f"\"{truncate(before['quote'], 120)}\" → "
                         f"`{after['date']}` {STANCE_ARROW[after['stance']]} "
                         f"\"{truncate(after['quote'], 120)}\"")
        lines += ["", f"_See all people's shifts in "
                  f"{rel_link(path, 'Syntheses/Opinion-Shifts', 'Syntheses/Opinion Shifts')}._", ""]

    # --- disagreements with others ------------------------------------------
    others = []
    for t in topics:
        rec = TOPICS.get(t["key"])
        if not rec:
            continue
        opposing = [n for n, evs in rec["per_person"].items()
                    if n != name and evs
                    and {evs[-1]["stance"], t["current"]} == {"bullish", "bearish"}]
        if opposing:
            others.append((t, opposing))
    if others:
        lines += [
            "## Where others disagree",
            "",
            "Topics where this person's current stance conflicts with "
            "another person's:",
            "",
        ]
        for t, opposing in others:
            who = ", ".join(person_link(path, n) for n in opposing[:6])
            lines.append(f"- {topic_link(path, t)} — opposite: {who}")
        lines += ["", f"_Full both-sides breakdown: "
                  f"{rel_link(path, 'Syntheses/Disagreements', 'Syntheses/Disagreements')}._", ""]

    lines += [
        "---",
        f"_Page reflects DB state at generation time. Regenerate via "
        "`uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page(rel, "\n".join(lines))


def render_theme(theme: dict) -> Path:
    slug = theme["slug"]
    rel = f"Themes/{slug}.md"
    path = WIKI_DIR / rel
    preds = preds_for_theme(slug)
    views = views_for_theme(slug)

    # constituent tickers (from preds)
    tk_counter = Counter((k for k in (_topic_key(p) for p in preds) if k))
    tickers = tk_counter.most_common()

    # key voices: people with the most events in this theme
    voice_counter: Counter[str] = Counter()
    for p in preds:
        nm = resolve_person(p.get("speaker") or "")
        if nm:
            voice_counter[nm] += 1
    for v in views:
        nm = resolve_person(v.get("speaker") or "")
        if nm:
            voice_counter[nm] += 1

    lines = [
        f"# Theme: {theme['title']}",
        "",
        theme["blurb"],
        "",
        f"**{len(preds)} prediction(s)** and **{len(views)} market view(s)** "
        f"match this theme in the current extraction.",
        "",
        "## Constituent tickers",
        "",
    ]
    if tickers:
        lines += ["| Ticker | Mentions |", "|---|---:|"]
        for tk, n in tickers:
            plist = group_predictions_by_ticker(DATA["preds"]).get(tk, [])
            if len(plist) >= MIN_TICKER_MENTIONS:
                link = rel_link(path, f"Tickers/{topic_page_file(tk)}", tk)
            else:
                link = f"`{tk}`"
            lines.append(f"| {link} | {n} |")
        lines.append("")
    else:
        lines += ["_No tickered predictions fall in this theme yet (signal "
                  "comes from market-view asset_class text only)._", ""]
    if voice_counter:
        lines += ["## Key voices", ""]
        for nm, n in voice_counter.most_common(10):
            lines.append(f"- {person_link(path, nm)} ({n})")
        lines.append("")
    # consensus across predictions
    if preds:
        stances = [stance(p.get("action"), p.get("direction")) for p in preds]
        n_bull = sum(1 for s in stances if s == "bullish")
        n_bear = sum(1 for s in stances if s == "bearish")
        lines += [
            "## Consensus across analysts",
            "",
            f"Of {len(preds)} tickered calls: **{n_bull} bullish**, "
            f"**{n_bear} bearish**.",
            "",
        ]
    lines += ["## Notable calls & quotes", ""]
    seen = set()
    for p in preds[:12]:
        key = p.get("id")
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"- {item_citation(path, p)}")
    if views:
        lines += ["", "## Broad market views", ""]
        seen_v = set()
        for v in views[:10]:
            key = v.get("id")
            if key in seen_v:
                continue
            seen_v.add(key)
            ac = v.get("asset_class") or "?"
            d = v.get("direction") or "?"
            lines.append(f"- _{md_escape(ac)} ({md_escape(d)})_: "
                         f"{item_citation(path, v)}")
    lines += [
        "",
        "---",
        f"_Theme buckets are keyword-based and approximate; an LLM-tagged "
        "taxonomy would be more precise. Regenerate via "
        "`uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page(rel, "\n".join(lines))


# ---------------------------------------------------------------------------
# Syntheses — the multi-dimensional views
# ---------------------------------------------------------------------------

def render_opinion_shifts() -> Path:
    """Same person, same topic, opposite stances at different times."""
    path = WIKI_DIR / "Syntheses" / "Opinion-Shifts.md"
    entries: list[tuple[str, dict, tuple[dict, dict]]] = []
    for name, person in sorted(PEOPLE.items()):
        for t in person_topics(person):
            for f in t["flips"]:
                entries.append((name, t, f))
    entries.sort(key=lambda x: x[2][1]["date"], reverse=True)
    lines = [
        "# Synthesis: Opinion Shifts",
        "",
        "Where the **same person** has taken opposite stances on the same "
        "topic at different times — the corpus's clearest evidence of "
        "changing minds. Newest flip first.",
        "",
    ]
    if not entries:
        lines.append("_No stance flips detected in the current extraction "
                     "(this will populate as more items are extracted)._")
    else:
        for name, t, (before, after) in entries:
            lines += [
                f"## {person_link(path, name)} — {topic_link(path, t)}",
                "",
                f"- **Before** (`{before['date']}`, {STANCE_ARROW[before['stance']]}): "
                f"\"{truncate(before['quote'], 200) or '_(no quote)'}\"",
                f"- **After** (`{after['date']}`, {STANCE_ARROW[after['stance']]}): "
                f"\"{truncate(after['quote'], 200) or '_(no quote)'}\"",
                "",
            ]
    lines += [
        "---",
        "_Derived from per-person topic timelines. Regenerate via "
        "`uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page("Syntheses/Opinion-Shifts.md", "\n".join(lines))


def render_disagreements() -> Path:
    """Different people on opposite sides of the same topic."""
    path = WIKI_DIR / "Syntheses" / "Disagreements.md"
    sections: list[tuple[dict, list[tuple[str, str, dict]]]] = []
    for key, t in TOPICS.items():
        # each person's latest directional stance on the topic
        latest: dict[str, tuple[str, dict]] = {}
        for n, evs in t["per_person"].items():
            for e in reversed(evs):
                if e["stance"] != "neutral":
                    latest[n] = (e["stance"], e)
                    break
        bulls = [(n, e) for n, (s, e) in latest.items() if s == "bullish"]
        bears = [(n, e) for n, (s, e) in latest.items() if s == "bearish"]
        if bulls and bears:
            rows = ([(n, "bullish", e) for n, e in bulls]
                    + [(n, "bearish", e) for n, e in bears])
            sections.append((t, rows))
    sections.sort(key=lambda x: -len(x[1]))

    lines = [
        "# Synthesis: Disagreements",
        "",
        "Topics where **different people** currently hold opposite stances "
        "(each person's latest directional call on the topic). Sorted by "
        "how many voices are in the fight.",
        "",
    ]
    if not sections:
        lines.append("_No cross-person conflicts detected in the current "
                     "extraction._")
    for t, rows in sections:
        lines += [f"## {topic_link(path, t)}", ""]
        for n, s, e in rows:
            lines.append(f"- {person_link(path, n)} — {STANCE_ARROW[s]} "
                         f"(`{e['date']}`): "
                         f"\"{truncate(e['quote'], 160) or '_(no quote)'}\"")
        lines.append("")
    lines += [
        "---",
        "_'Current' = each person's most recent non-neutral extracted call. "
        "Regenerate via `uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page("Syntheses/Disagreements.md", "\n".join(lines))


def render_timeline() -> Path:
    """Every extracted call, chronological — the time dimension."""
    events: list[tuple[str, str, dict]] = []
    for name, person in PEOPLE.items():
        for t in person_topics(person):
            for e in t["events"]:
                events.append((e["date"] or "9999", name, e))
    events.sort(key=lambda x: x[0])

    lines = [
        "# Synthesis: Timeline of Calls",
        "",
        f"Every attributed extracted call ({len(events)} events, oldest → "
        "newest), grouped by year. Use this to read any topic with the "
        "time dimension in view.",
        "",
    ]
    cur_year = None
    for date, name, e in events:
        y = date[:4]
        if y != cur_year:
            cur_year = y
            lines += [f"## {y}", ""]
        arrow = STANCE_ARROW[e["stance"]].split(" ")[0]
        lines.append(f"- `{date}` **{md_escape(name)}** {arrow} "
                     f"{md_escape(e['topic_label'])} — "
                     f"{truncate(e['quote'], 140) or '_(no quote)'}")
    lines += [
        "",
        "---",
        "_Regenerate via `uv run python scripts/build_llm_wiki.py`._",
    ]
    return write_page("Syntheses/Timeline.md", "\n".join(lines))


def render_index(pages: dict[str, list[tuple[str, str]]]) -> Path:
    """pages[section] is a list of (slug, display_label)."""
    lines = [
        "# Index",
        "",
        "Every page in the wiki, alphabetical by display label within each "
        "section.",
        "",
        "## People",
        "",
    ]
    for slug, label in sorted(pages.get("People", []), key=lambda x: x[1].lower()):
        lines.append(f"- [{md_escape(label)}](People/{slug}.md)")
    lines += ["", "## Tickers", ""]
    for slug, label in sorted(pages.get("Tickers", []), key=lambda x: x[1].lower()):
        lines.append(f"- [{md_escape(label)}](Tickers/{slug}.md)")
    lines += ["", "## Themes", ""]
    for slug, label in sorted(pages.get("Themes", []), key=lambda x: x[1].lower()):
        lines.append(f"- [{md_escape(label)}](Themes/{slug}.md)")
    lines += ["", "## Syntheses", ""]
    for slug, label in sorted(pages.get("Syntheses", []), key=lambda x: x[1].lower()):
        lines.append(f"- [{md_escape(label)}](Syntheses/{slug}.md)")
    lines += ["", "## Analysts", ""]
    for slug, label in sorted(pages.get("Analysts", []), key=lambda x: x[1].lower()):
        lines.append(f"- [{md_escape(label)}](Analysts/{slug}.md)")
    lines += ["", "[← Back to Home](Home.md)", ""]
    return write_page("_Index.md", "\n".join(lines))


def render_readme(inv: dict, counts: dict[str, int]) -> Path:
    t = inv["totals"]
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# llm-wiki",
        "",
        "A Karpathy-style synthesized wiki generated **from** the "
        "`knowledge_base` Postgres database. Not hand-written — every page is "
        "rendered by `scripts/build_llm_wiki.py` from the `item`, `prediction`, "
        "`view_market`, `channel`, `source` tables and the per-item speaker "
        "lists in `extraction_run`.",
        "",
        "## Regenerate",
        "",
        "```bash",
        "# from the repo root, with the postgres container running",
        "uv run python scripts/build_llm_wiki.py",
        "# add --no-bios to skip LLM bio generation for People pages",
        "```",
        "",
        "The script is **read-only** against the DB and only writes under "
        "`llm-wiki/` (plus the bio cache `scripts/llm_wiki_bios.json`, so "
        "bios are only generated once per person). The build is "
        "**incremental**: files are only rewritten when their content "
        "changes, stale generated pages are garbage-collected, and any "
        "other files you keep here are left alone.",
        "",
        "## What it produces",
        "",
        "```",
        "llm-wiki/",
        "  Home.md             # overview + DB stats + caveats + marquee pages",
        "  _Index.md           # alphabetical index",
        "  README.md           # this file",
        "  AGENTS.md           # agent notes (also generated — don't hand-edit)",
        f"  People/    ({counts.get('People',0)} pages)   # one per person (guests, hosts,",
        "                        #   solo authors merged across shows) — opinions",
        "                        #   per topic over time, flips flagged, LLM bios",
        f"  Tickers/   ({counts.get('Tickers',0)} pages)   # one per ticker >= {MIN_TICKER_MENTIONS} mentions,",
        "                        #   incl. rates/bond-yield backdrop",
        f"  Analysts/  ({counts.get('Analysts',0)} pages)   # one per channel with extracted items",
        f"  Themes/    ({counts.get('Themes',0)} pages)   # cross-cutting theses (gold, AI-semis, …)",
        f"  Syntheses/ ({counts.get('Syntheses',0)} pages)   # opinion shifts · disagreements · timeline",
        "```",
        "",
        "## Data snapshot at generation time",
        "",
        f"- Generated: **{ts}**",
        f"- Items in DB: **{t['n_items']:,}** (extracted: **{t['n_extracted']:,}**, "
        f"pending: **{t['n_pending']:,}**)",
        f"- Predictions: **{inv['n_preds']:,}** · Market views: **{inv['n_views']:,}**",
        f"- Distinct tickers with calls: **{inv['n_tickers']}** · People pages: **{counts.get('People',0)}**",
        f"- Published-date range: **{fmt_date(t['first_date'])} → {fmt_date(t['last_date'])}**",
        "",
        "## Important caveats",
        "",
        "1. **Coverage is thin.** The wiki reflects only the items the "
        "extraction pipeline has processed so far (a small fraction of the "
        "ingested corpus). It will get denser and more accurate as more items "
        "are extracted. **Re-run after each scrape/extraction batch.**",
        "2. **No performance scores.** Predictions carry `score` columns but "
        "none are evaluated yet (`n_scored=0`). There is no hit-rate / "
        "track-record data — only stated calls.",
        "3. **People bios are LLM-generated** (default provider: GLM via "
        "`zai`) from public knowledge + DB context, and cached. Stances, "
        "timelines, shifts and disagreements are strictly DB-derived from "
        "extracted quotes.",
        "4. **Themes are keyword-bucketed**, not semantically clustered — "
        "approximate by design.",
        "5. **Quotes are LLM-extracted**, not curated. They can misattribute "
        "or trim. Always follow the source-item link to verify.",
        "",
        "## How claims are cited",
        "",
        "Every prediction/view cites its source item by:",
        "- the item **title** (linked to its external URL — YouTube watch "
        "link, HKEJ article, Substack post, etc.),",
        "- the **published date**,",
        "- the **channel/analyst** name (and, where attributed, the person),",
        "- and where relevant, the extracted **quote**.",
        "",
        "The `external_id` (e.g. a YouTube video id) is the item's stable key "
        "in the DB; the URL is its public location.",
        "",
        "## Related",
        "",
        "- [Home](Home.md)",
        "- [_Index](_Index.md)",
        "- Repo root `AGENTS.md` for the full pipeline architecture.",
    ]
    return write_page("README.md", "\n".join(lines))


def render_agents() -> Path:
    """Agent-facing notes for the generated tree (rendered each run so it
    stays in sync with the generator)."""
    lines = [
        "# llm-wiki — agent notes",
        "",
        "**Every page here is generated.** Do not hand-edit pages — they are",
        "rewritten by `scripts/build_llm_wiki.py` whenever their content",
        "changes. To change anything, change the script (or the DB it",
        "reads) and re-run:",
        "",
        "```bash",
        "uv run python scripts/build_llm_wiki.py [--no-bios]",
        "```",
        "",
        "## Structure",
        "",
        "- `People/` — one page per person (interview guests, show hosts,",
        "  solo authors), merged across every show they appear on via",
        "  alias/generic-name resolution. Opinions per topic in chronological",
        "  order; stance flips (bullish→bearish across *different days*) are",
        "  flagged. GLM-written bios are cached in",
        "  `scripts/llm_wiki_bios.json` (pass `--no-bios` to skip generation;",
        "  failed lookups are retried on the next run).",
        "- `Tickers/` — one page per topic with >= "
        f"{MIN_TICKER_MENTIONS} predictions. Pages are keyed by Yahoo",
        "  symbol when the ticker is symbol-like, otherwise by the",
        "  asset/company name (the extract pipeline nulls non-symbol",
        "  tickers into `asset_name`, so fragments like \"PAN MINE\" become",
        "  name-keyed pages). Each page carries a rates/bond-yield backdrop",
        "  section for macro context.",
        "- `Analysts/` — one page per channel with extracted items, plus the",
        "  people who appear on it.",
        "- `Themes/` — hand-curated keyword buckets (CJK-aware matching); a",
        "  theme page only exists when the current extraction has matching",
        "  rows.",
        "- `Syntheses/` — cross-cutting views: Opinion Shifts (same person",
        "  changes stance), Disagreements (people on opposite sides of one",
        "  topic, each side's latest call), and the global Timeline.",
        "",
        "## Provenance rules",
        "",
        "- Stances, timelines, disagreements and counts are **strictly",
        "  DB-derived** from `item` / `prediction` / `view_market` /",
        "  `extraction_run.raw_response->speakers` — never synthesized.",
        "- Bios are the only LLM-written content and are marked as such on",
        "  the page.",
        "- Coverage mirrors extraction progress; the Home page states the",
        "  extracted/total fraction. Re-run after each `kb extract run`",
        "  batch.",
        "",
        "Wiki-wide conventions and the pipeline architecture live in the",
        "repo root `AGENTS.md`.",
    ]
    return write_page("AGENTS.md", "\n".join(lines))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    global DATA, PEOPLE, TOPICS
    ap = argparse.ArgumentParser(
        description="Build the llm-wiki from the knowledge database.")
    ap.add_argument("--no-bios", action="store_true",
                    help="skip LLM bio generation for People pages")
    ap.add_argument("--provider", default=None,
                    help="LLM provider for bios (default: LLM_PROVIDER, "
                         "i.e. the configured zai/GLM default)")
    ap.add_argument("--model", default=None,
                    help=f"LLM model for bios (zai default: {WIKI_ZAI_MODEL}; "
                         "other providers: their configured default)")
    args = ap.parse_args()

    print("loading data from DB …")
    DATA = fetch_all()
    print(f"  {len(DATA['preds'])} predictions, {len(DATA['views'])} views, "
          f"{len(DATA['analysts'])} channels with extractions, "
          f"{len(DATA['item_speakers'])} items with speaker lists")

    print("building people registry …")
    PEOPLE = build_people()
    n_multi = sum(1 for p in PEOPLE.values() if len(p["channels"]) > 1)
    print(f"  {len(PEOPLE)} people "
          f"({n_multi} appearing on more than one show)")

    bios = ensure_bios(no_llm=args.no_bios, provider=args.provider,
                       model=args.model)
    print(f"  bios cached/generated: {len(bios)}")

    TOPICS = build_topic_matrix()

    # Incremental build: the tree is never wiped. Pages are written (or
    # left as-is when unchanged) by the renderers; afterwards, pages a
    # previous run generated that this run no longer produces are removed
    # via the manifest. Anything else living in llm-wiki/ is untouched.
    WIKI_DIR.mkdir(parents=True, exist_ok=True)

    pages: dict[str, list[tuple[str, str]]] = {
        "People": [], "Tickers": [], "Analysts": [], "Themes": [],
        "Syntheses": []}

    # --- People ---
    for name in sorted(PEOPLE):
        person = PEOPLE[name]
        if not (person["appearances"] or person["n_events"]):
            continue
        render_person(person, bios)
        pages["People"].append((person["slug"], name))

    # --- Tickers ---
    by_tk = group_predictions_by_ticker(DATA["preds"])
    for tk, plist in sorted(by_tk.items()):
        p = render_ticker(tk, plist)
        if p:
            asset_name = next((pp.get("asset_name") for pp in plist
                               if pp.get("asset_name")), tk)
            label = (f"{tk} — {asset_name}" if SYMBOL_RE.match(tk)
                     and asset_name != tk else tk)
            pages["Tickers"].append((topic_page_file(tk), label))

    # --- Analysts ---
    for a in DATA["analysts"]:
        render_analyst(a)
        pages["Analysts"].append(
            (channel_slug(a), a.get("channel_name") or a.get("channel_handle") or "?"))

    # --- Themes ---
    for theme in THEMES:
        # only emit a theme page if it has any preds or views
        if preds_for_theme(theme["slug"]) or views_for_theme(theme["slug"]):
            render_theme(theme)
            pages["Themes"].append((theme["slug"], theme["title"]))

    # --- Syntheses ---
    render_opinion_shifts()
    pages["Syntheses"].append(
        ("Opinion-Shifts", "Opinion Shifts (same person changes mind)"))
    render_disagreements()
    pages["Syntheses"].append(
        ("Disagreements", "Disagreements (people vs people)"))
    render_timeline()
    pages["Syntheses"].append(("Timeline", "Timeline of Calls (global)"))

    # --- Home, Index, README, AGENTS ---
    counts = {k: len(v) for k, v in pages.items()}
    render_home(DATA, counts)
    render_index(pages)
    render_readme(DATA, counts)
    render_agents()

    # --- garbage-collect pages that no longer exist ----------------------
    prev: set[str] = set()
    if MANIFEST.exists():
        try:
            prev = set(json.loads(MANIFEST.read_text(encoding="utf-8")))
        except Exception:  # noqa: BLE001 — corrupt manifest: just skip GC
            prev = set()
    removed = 0
    for rel in sorted(prev - WRITTEN):
        p = WIKI_DIR / rel
        if p.exists():
            p.unlink()
            print(f"  removed stale page: {rel}")
            removed += 1
    # prune directories the removals may have emptied (bottom-up)
    for d in sorted((p for p in WIKI_DIR.rglob("*") if p.is_dir()),
                    reverse=True):
        try:
            d.rmdir()
        except OSError:
            pass
    MANIFEST.write_text(json.dumps(sorted(WRITTEN), indent=0) + "\n",
                        encoding="utf-8")

    print(f"\nwiki written to {WIKI_DIR} "
          f"({len(WRITTEN)} pages, {removed} stale removed)")
    for k in ("People", "Tickers", "Analysts", "Themes", "Syntheses"):
        print(f"  {k:<10} {counts[k]}")


if __name__ == "__main__":
    main()
